
#ifndef SWEEP_VERSION_H
#define SWEEP_VERSION_H

# define SWEEP_TITLE "Sweep"
# define SWEEP_AUTHOR "Zohar \"dotfloat\" Malamant"
# define SWEEP_DESC "A Minesweeper Clone"

# define SWEEP_VERMAJOR 0
# define SWEEP_VERMINOR 0
# define SWEEP_VERFULL "0.0"

# define SWEEP_FULLTITLE SWEEP_TITLE " - " SWEEP_DESC

# define SWEEP_WTEXT(x) L##x
# define SWEEP_WTITLE SWEEP_WTEXT(SWEEP_TITLE)
# define SWEEP_WAUTHOR SWEEP_WTEXT(SWEEP_AUTHOR)
# define SWEEP_WDESC SWEEP_WTEXT(SWEEP_DESC)
# define SWEEP_WVERFULL SWEEP_WTEXT(SWEEP_VERFULL)
# define SWEEP_WFULLTITLE SWEEP_WTEXT(SWEEP_WFULLTITLE)

#endif // SWEEP_VERSION_H
